[package]
name = "context_data_structures"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "context_data_structures"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
uuid.workspace = true
url.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
contextapi-workspace-hack = { version = "0.1", path = "../contextapi-workspace-hack" }

[features]
machine_properties = ["aliases"]
network_setup = ["aliases"]
rsd = ["aliases"]
aliases = []
default = ["aliases", "machine_properties", "network_setup", "rsd"]
