[package]
authors.workspace = true
description = "Shared data structures for the Context API"
edition.workspace = true
license.workspace = true
name = "context_data_structures"
publish = false
repository.workspace = true
version = "0.1.0"

[lib]
name = "context_data_structures"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
uuid.workspace = true
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
