[package]
authors.workspace = true
default-run = "remote-serial"
description = "Manage serial connections to remote devices under test"
edition.workspace = true
license.workspace = true
name = "remote-serial"
publish = false
readme = "README.md"
repository.workspace = true
version = "1.0.0"

[lib]
name = "remote_serial"
path = "src/lib.rs"

[[bin]]
name = "remote-serial"
path = "src/main.rs"

[[bin]]
name = "remote-serial-openapi-generator"
path = "src/bin/openapi-generator.rs"

[lints]
workspace = true

[dependencies]
aide.workspace = true
axum.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serial2-tokio.workspace = true
remote-axum.workspace = true
remote-init.workspace = true
tracing.workspace = true
tokio.workspace = true
futures.workspace = true
tokio-util.workspace = true

[dev-dependencies]
tokio-test.workspace = true
bytes.workspace = true
tower.workspace = true
tokio-tungstenite.workspace = true
dashmap.workspace = true
axum-test.workspace = true
