[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "error_utils"
publish = false
readme = "README.md"
repository.workspace = true
version = "0.1.0"

[lib]
name = "error_utils"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
tracing.workspace = true
