[package]
name = "db_interaction"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "db_interaction"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
chrono.workspace = true
context_data_structures = { workspace = true, features = ["aliases"] }
deadpool-diesel.workspace = true
diesel.workspace = true
diesel_migrations.workspace = true
either.workspace = true
schemars.workspace = true
serde.workspace = true
strum_macros.workspace = true
tokio.workspace = true
uuid.workspace = true
contextapi-workspace-hack = { version = "0.1", path = "../contextapi-workspace-hack" }

[features]
test_utils = ["assert_fs"]

[dependencies.assert_fs]
optional = true
workspace = true
