[package]
edition = "2021"
name = "net-ctrl"
version = "0.1.0"
license = "Apache-2.0"

[workspace]
resolver = "3"
members = [
  "connection_handler",
  "inventory",
  "net-ctrl-workspace-hack",
  "network_type_ids",
  "switch",
]

[lib]
name = "net_ctrl_lib"
path = "src/lib.rs"

[[bin]]
name = "net-ctrl"
path = "src/main.rs"

[[bin]]
name = "net-ctrl-openapi-generator"
path = "src/bin/openapi-generator.rs"

[[bin]]
name = "net-ctrl-config-schema-generator"
path = "src/bin/config-schema-generator.rs"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
aide = { version = "0.13.4", features = ["axum", "axum-extra", "macros"] }
axum = { version = "0.7", features = ["multipart", "ws"] }
clap = { version = "4.2.0", features = ["derive"] }
connection_handler = { path = "./connection_handler" }
error-stack = "0.4"
hunt = { path = "../hunt" }
inventory = { path = "./inventory" }
log = "0.4.21"
network_type_ids = { path = "./network_type_ids", features = ["serde_support"] }
# NOTE(hartan): This is only a transient dependency, but we specify it here to
# define the features we expect once. Otherwise, it appears the
# `default-features` are set, which will pull in `aws-lc-sys` as additional
# crypto backend next to `ring`, which is already requested by other crates we
# use.
rustls = { version = "0.23", default-features = false, features = [
  "std",
  "ring",
] }
schemars = "0.8"
sd-notify = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
switch = { path = "./switch" }
system_error = "0.2.0"
tokio = { version = "1.24.1", features = [
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "signal",
  "sync",
  "tracing",
] }
tracing = "0.1"
net-ctrl-workspace-hack = { version = "0.1", path = "net-ctrl-workspace-hack" }

[dev-dependencies]
reqwest = { version = "*", default-features = false }
env_logger = "0.11.3"                                 # required by test-log
network_type_ids = { path = "./network_type_ids" }
pretty_assertions = "1.2.1"
serde_json = "1.0"
test-log = "0.2"

[package.metadata.cargo-udeps.ignore]
development = ["pretty_assertions"]
