[package]
authors.workspace = true
description = "On-demand network configuration"
edition.workspace = true
license.workspace = true
name = "net-ctrl"
publish = false
readme = "README.md"
repository.workspace = true
version = "0.1.0"


[lib]
name = "net_ctrl_lib"
path = "src/lib.rs"

[[bin]]
name = "net-ctrl"
path = "src/main.rs"

[[bin]]
name = "net-ctrl-openapi-generator"
path = "src/bin/openapi-generator.rs"

[[bin]]
name = "net-ctrl-config-schema-generator"
path = "src/bin/config-schema-generator.rs"

[lints]
workspace = true

[dependencies]
aide.workspace = true
async-trait.workspace = true
axum.workspace = true
base64.workspace = true
clap.workspace = true
dashmap.workspace = true
enum_dispatch.workspace = true
error-stack.workspace = true
http.workspace = true
hunt.workspace = true
libc.workspace = true
reqwest.workspace = true
reqwest-middleware.workspace = true
reqwest_cookie_store.workspace = true
schemars.workspace = true
sd-notify.workspace = true
serde.workspace = true
serde_json.workspace = true
system_error.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
axum-test-helper.workspace = true
test-log.workspace = true
