[package]
authors.workspace = true
description = "Manage and provide BMR boot images"
edition.workspace = true
license.workspace = true
name = "image_api"
publish = false
readme = "README.md"
repository.workspace = true
version = "0.1.0"

[lib]
name = "image_api"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
context_data_structures.workspace = true
axum.workspace = true
tracing.workspace = true
tower-http.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tokio-stream.workspace = true
futures.workspace = true
sha2.workspace = true
serde.workspace = true
uuid.workspace = true
regex.workspace = true
bytes.workspace = true
aide.workspace = true
schemars.workspace = true
bytesize.workspace = true
async-compression.workspace = true

[dev-dependencies]
tempfile.workspace = true
