/*
 * 
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration, ContentType};


/// struct for typed errors of method [`switches_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SwitchesGetError {
    Status400(),
    Status401(),
    Status404(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`switches_switch_id_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SwitchesSwitchIdGetError {
    Status400(),
    Status401(),
    Status404(),
    Status410(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`switches_switch_id_ports_port_id_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SwitchesSwitchIdPortsPortIdDeleteError {
    Status400(),
    Status401(),
    Status404(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`switches_switch_id_ports_port_id_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SwitchesSwitchIdPortsPortIdPutError {
    Status400(),
    Status401(),
    Status404(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`switches_switch_id_setup_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SwitchesSwitchIdSetupPostError {
    Status400(),
    Status401(),
    Status404(),
    Status410(),
    Status500(),
    Status502(),
    Status503(),
    Status504(),
    UnknownValue(serde_json::Value),
}


/// Get all switch IDs from the inventory
pub async fn switches_get(configuration: &configuration::Configuration, ) -> Result<std::collections::HashMap<String, models::SwitchModelDetail>, Error<SwitchesGetError>> {

    let uri_str = format!("{}/switches", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::SwitchModelDetail&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `std::collections::HashMap&lt;String, models::SwitchModelDetail&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SwitchesGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Get information about a switch
pub async fn switches_switch_id_get(configuration: &configuration::Configuration, switch_id: &str) -> Result<Vec<models::PortRepresentation>, Error<SwitchesSwitchIdGetError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_switch_id = switch_id;

    let uri_str = format!("{}/switches/{switch_id}", configuration.base_path, switch_id=p_path_switch_id.to_string());
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();
    let content_type = resp
        .headers()
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .unwrap_or("application/octet-stream");
    let content_type = super::ContentType::from(content_type);

    if !status.is_client_error() && !status.is_server_error() {
        let content = resp.text().await?;
        match content_type {
            ContentType::Json => serde_json::from_str(&content).map_err(Error::from),
            ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `Vec&lt;models::PortRepresentation&gt;`"))),
            ContentType::Unsupported(unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{unknown_type}` content type response that cannot be converted to `Vec&lt;models::PortRepresentation&gt;`")))),
        }
    } else {
        let content = resp.text().await?;
        let entity: Option<SwitchesSwitchIdGetError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Disable a switch port and un-assign VLAN
pub async fn switches_switch_id_ports_port_id_delete(configuration: &configuration::Configuration, port_id: &str, switch_id: &str) -> Result<(), Error<SwitchesSwitchIdPortsPortIdDeleteError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_port_id = port_id;
    let p_path_switch_id = switch_id;

    let uri_str = format!("{}/switches/{switch_id}/ports/{port_id}", configuration.base_path, port_id=p_path_port_id.to_string(), switch_id=p_path_switch_id.to_string());
    let mut req_builder = configuration.client.request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<SwitchesSwitchIdPortsPortIdDeleteError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// Enable a switch port and assign a VLAN
pub async fn switches_switch_id_ports_port_id_put(configuration: &configuration::Configuration, port_id: &str, switch_id: &str, vlan_id: models::VlanId) -> Result<(), Error<SwitchesSwitchIdPortsPortIdPutError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_port_id = port_id;
    let p_path_switch_id = switch_id;
    let p_body_vlan_id = vlan_id;

    let uri_str = format!("{}/switches/{switch_id}/ports/{port_id}", configuration.base_path, port_id=p_path_port_id.to_string(), switch_id=p_path_switch_id.to_string());
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_vlan_id);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<SwitchesSwitchIdPortsPortIdPutError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

/// setup VLANs and trunk ports
pub async fn switches_switch_id_setup_post(configuration: &configuration::Configuration, switch_id: &str, setup_data: models::SetupData) -> Result<(), Error<SwitchesSwitchIdSetupPostError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_switch_id = switch_id;
    let p_body_setup_data = setup_data;

    let uri_str = format!("{}/switches/{switch_id}/setup", configuration.base_path, switch_id=p_path_switch_id.to_string());
    let mut req_builder = configuration.client.request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.json(&p_body_setup_data);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if !status.is_client_error() && !status.is_server_error() {
        Ok(())
    } else {
        let content = resp.text().await?;
        let entity: Option<SwitchesSwitchIdSetupPostError> = serde_json::from_str(&content).ok();
        Err(Error::ResponseError(ResponseContent { status, content, entity }))
    }
}

