export { default as GlobeIcon } from './Globe.vue'
export { default as ChipIcon } from './Chip.vue'
export { default as CloudIcon } from './Cloud.vue'
export { default as CubeIcon } from './Cube.vue'
export { default as SettingsIcon } from './Settings.vue'
export { default as UploadIcon } from './Upload.vue'
