[package]
authors.workspace = true
description = "HWaaS NetCtrl API"
edition.workspace = true
license.workspace = true
name = "net_ctrl_client"
publish = false
readme = "README.md"
repository.workspace = true
version = "0.1.0"

[lib]
name = "net_ctrl_client"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
serde.workspace = true
serde_with.workspace = true
serde_json.workspace = true
url.workspace = true
uuid.workspace = true
reqwest.workspace = true
reqwest-middleware.workspace = true
