[package]
authors.workspace = true
description = "HWaaS universal notorious tracing (Hunt) is a default tracing setup used by HWaaS rust components"
edition.workspace = true
license.workspace = true
name = "hunt"
publish = false
readme = "README.md"
repository.workspace = true
version = "0.1.0"

[lib]
name = "hunt"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "hunt-test-app"
path = "src/bin/hunt-test-app.rs"

[lints]
workspace = true

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest", "dep:reqwest-middleware"]
tower = []

[dependencies]
axum-tracing-opentelemetry.workspace = true
axum.workspace = true
console-subscriber.workspace = true
futures.workspace = true
init-tracing-opentelemetry.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
reqwest-middleware = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
task-local-extensions.workspace = true
tower-http.workspace = true
tower.workspace = true
tracing-journald.workspace = true
tracing-opentelemetry-instrumentation-sdk.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
