[package]
name = "hunt"
version = "0.1.0"
edition = "2021"
description = "HWaaS universal notorious tracing (Hunt) is a default tracing setup used by HWaaS rust components"
license = "Apache-2.0"

[lib]
name = "hunt"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "hunt-test-app"
path = "src/bin/hunt-test-app.rs"

[lints.rust]
unsafe_code = "forbid"

[features]
default = ["reqwest"]
reqwest = ["dep:reqwest", "dep:reqwest-middleware"]
tower = []

[dependencies]
axum-tracing-opentelemetry = { version = "0.18.1" }
tracing-opentelemetry = "0.23.0"
opentelemetry = { version = "0.22.0", features = ["trace"] }
tracing-journald = "0.3.0"
tracing-subscriber = { version = "0.3", features = [
  "ansi",
  "env-filter",
  "fmt",
  "json",
] }
console-subscriber = "0.2"
tracing = "0.1"
tower = "0.4"
tower-http = { version = "0.5.2", default-features = false, features = [
  "trace",
  "request-id",
  "limit",
  "timeout",
] }
axum = "0.7"
futures = "0.3"
reqwest-middleware = { version = "0.5", optional = true }
reqwest = { version = "0.13", optional = true, default-features = false }
task-local-extensions = "0.1"
init-tracing-opentelemetry = { version = "0.18.1", features = [
  "tracing_subscriber_ext",
  "otlp",
] }
tracing-opentelemetry-instrumentation-sdk = "0.18.1"
opentelemetry_sdk = "0.22.1"
