[package]
authors.workspace = true
default-run = "remote-usb"
description = "Manage USB connections for remote devices under test"
edition.workspace = true
license.workspace = true
name = "remote-usb"
publish = false
readme = "README.md"
repository.workspace = true
version = "1.0.0"


[lib]
name = "remote_usb"
path = "src/lib.rs"

[[bin]]
name = "remote-usb"
path = "src/main.rs"

[[bin]]
name = "remote-usb-openapi-generator"
path = "src/bin/openapi-generator.rs"

[features]
# Optional because deconfiguring USB serial leaves the kernel with
# hung tasks
usb-serial = []
# Optional since we still need a design for the incorporation into the test
# network. Currently only enables network between pi and machine under test.
usb-ethernet = []

[lints]
workspace = true

[dependencies]
aide.workspace = true
axum.workspace = true
hidg.workspace = true
itertools.workspace = true
remote-axum.workspace = true
remote-init.workspace = true
remote-serial.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
usb-gadget.workspace = true
usbd-hid-macros.workspace = true
