[workspace]
resolver = "3"
members = [
  "aruba-switch-mock",
  "hunt",
  "rpi-status-display",
]

[workspace.package]
authors = ["secunet Security Networks AG <https://www.secunet.com>"]
edition = "2024"
license = "Apache-2.0"
publish = false
readme = "../README.md"
repository = "https://github.com/secunet-AG/hwaas"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
# NOTE: Due to some weird interaction in the Rust toolchain it's not currently possible to "forbid"
# clippy lints unconditionally. See: <https://github.com/rust-lang/rust/issues/81670>
all = "deny"

[workspace.dependencies]
axum = "0.7"
axum-tracing-opentelemetry = "0.18.1"
clap = { version = "4.3.4", features = ["derive"] }
console-subscriber = "0.2"
dashmap = { version = "5.4", features = ["serde"] }
embedded-graphics = "0.8.0"
embedded-hal = "1.0.0-alpha.9"
futures = "0.3"
init-tracing-opentelemetry = { version = "0.18.1", features = [
  "tracing_subscriber_ext",
  "otlp",
] }
opentelemetry = { version = "0.22.0", features = ["trace"] }
opentelemetry_sdk = "0.22.1"
reqwest = { version = "0.12.4" }
reqwest-middleware = { version = "0.4" }
rppal = { version = "0.14.1", features = ["hal"] }
schemars = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sh1106 = "0.5.0"
ssd1306 = "0.8.0"
tracing-opentelemetry-instrumentation-sdk = "0.18.1"
task-local-extensions = "0.1"
tokio = { version = "1.23", features = [
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
  "tracing",
  "signal",
] }
tower = "0.5.0"
tower-cookies = "0.10.0"
tower-http = { version = "0.5.2", default-features = false, features = [
  "trace",
  "request-id",
  "limit",
  "timeout",
] }
tracing = "0.1"
tracing-journald = "0.3.0"
tracing-opentelemetry = "0.23.0"
tracing-subscriber = { version = "0.3", features = [
  "ansi",
  "env-filter",
  "fmt",
  "json",
] }
uuid = { version = "1.2", features = ["v4"] }
