[package]
authors.workspace = true
description = "Shared bootstrapping of CLI and config file handling for remote-hands components"
edition.workspace = true
license.workspace = true
name = "remote-init"
publish = false
readme = "README.md"
repository.workspace = true
version = "1.0.0"

[lib]
name = "remote_init"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
clap.workspace = true
hunt.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
