/*
 * 
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Credentials {
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "username")]
    pub username: String,
}

impl Credentials {
    pub fn new(password: String, username: String) -> Credentials {
        Credentials {
            password,
            username,
        }
    }
}

