/*
 * 
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CriticalPorts {
    #[serde(rename = "mgmt_ports")]
    pub mgmt_ports: Vec<String>,
    #[serde(rename = "trunk_ports")]
    pub trunk_ports: Vec<String>,
}

impl CriticalPorts {
    pub fn new(mgmt_ports: Vec<String>, trunk_ports: Vec<String>) -> CriticalPorts {
        CriticalPorts {
            mgmt_ports,
            trunk_ports,
        }
    }
}

