/*
 * 
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PathParamsSwitchAndPortId {
    /// PortID of the switch
    #[serde(rename = "port_id")]
    pub port_id: String,
    /// ID of a switch
    #[serde(rename = "switch_id")]
    pub switch_id: String,
}

impl PathParamsSwitchAndPortId {
    pub fn new(port_id: String, switch_id: String) -> PathParamsSwitchAndPortId {
        PathParamsSwitchAndPortId {
            port_id,
            switch_id,
        }
    }
}

