// SPDX-FileCopyrightText: Copyright 2026 secunet Security Networks AG <https://www.secunet.com>
//
// SPDX-License-Identifier: Apache-2.0

/*
 *
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PathParamsSwitchId {
    /// Contains information used to globally identify a switch.
    #[serde(rename = "switch_id")]
    pub switch_id: String,
}

impl PathParamsSwitchId {
    pub fn new(switch_id: String) -> PathParamsSwitchId {
        PathParamsSwitchId { switch_id }
    }
}
