// SPDX-FileCopyrightText: Copyright 2026 secunet Security Networks AG <https://www.secunet.com>
//
// SPDX-License-Identifier: Apache-2.0

/*
 *
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortRepresentation {
    /// Wrapper type for Port IDs. Can hold different ID types for different switch models. Generic Port ID used for all switch models. Individual conversion should be handled in the switch APIs.
    #[serde(rename = "port_id")]
    pub port_id: String,
}

impl PortRepresentation {
    pub fn new(port_id: String) -> PortRepresentation {
        PortRepresentation { port_id }
    }
}
