/*
 * 
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PortRepresentation {
    /// Local ID of a port.
    #[serde(rename = "port_id")]
    pub port_id: String,
}

impl PortRepresentation {
    pub fn new(port_id: String) -> PortRepresentation {
        PortRepresentation {
            port_id,
        }
    }
}

