// SPDX-FileCopyrightText: Copyright 2026 secunet Security Networks AG <https://www.secunet.com>
//
// SPDX-License-Identifier: Apache-2.0

/*
 *
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RangeOfUint16 {
    #[serde(rename = "end")]
    pub end: i32,
    #[serde(rename = "start")]
    pub start: i32,
}

impl RangeOfUint16 {
    pub fn new(end: i32, start: i32) -> RangeOfUint16 {
        RangeOfUint16 { end, start }
    }
}
