/*
 *
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SetupData : The user provided input for switch setup. Contains a range of u16 representing the allowed VLAN IDs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetupData {
    #[serde(rename = "vlan_id_range")]
    pub vlan_id_range: Box<models::RangeOfUint16>,
}

impl SetupData {
    /// The user provided input for switch setup. Contains a range of u16 representing the allowed VLAN IDs.
    pub fn new(vlan_id_range: models::RangeOfUint16) -> SetupData {
        SetupData {
            vlan_id_range: Box::new(vlan_id_range),
        }
    }
}
