/*
 * 
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SwitchModelDetail : Container for the information to construct a new SwitchAPI. The [`SwitchModel`] is used for determining the correct SwitchAPI type. The [`SwitchDetails`] contains all information needed by one SwitchAPI.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SwitchModelDetail {
    #[serde(rename = "credentials", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Option<Box<models::Credentials>>>,
    #[serde(rename = "critical_ports")]
    pub critical_ports: Box<models::CriticalPorts>,
    #[serde(rename = "default_vlan")]
    pub default_vlan: Box<models::VlanId>,
    #[serde(rename = "ip")]
    pub ip: String,
    #[serde(rename = "mgmt_vlan")]
    pub mgmt_vlan: Box<models::VlanId>,
    #[serde(rename = "model")]
    pub model: models::SwitchModel,
    #[serde(rename = "port", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub port: Option<Option<i32>>,
}

impl SwitchModelDetail {
    /// Container for the information to construct a new SwitchAPI. The [`SwitchModel`] is used for determining the correct SwitchAPI type. The [`SwitchDetails`] contains all information needed by one SwitchAPI.
    pub fn new(critical_ports: models::CriticalPorts, default_vlan: models::VlanId, ip: String, mgmt_vlan: models::VlanId, model: models::SwitchModel) -> SwitchModelDetail {
        SwitchModelDetail {
            credentials: None,
            critical_ports: Box::new(critical_ports),
            default_vlan: Box::new(default_vlan),
            ip,
            mgmt_vlan: Box::new(mgmt_vlan),
            model,
            port: None,
        }
    }
}

