// SPDX-FileCopyrightText: Copyright 2026 secunet Security Networks AG <https://www.secunet.com>
//
// SPDX-License-Identifier: Apache-2.0

/*
 *
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize, Default,
)]
pub enum SwitchModel {
    #[serde(rename = "aruba")]
    #[default]
    Aruba,
    #[serde(rename = "aruba2540")]
    Aruba2540,
    #[serde(rename = "aruba-aos-cx")]
    ArubaAosCx,
    #[serde(rename = "aruba-cx6100")]
    ArubaCx6100,
    #[serde(rename = "fs-picos")]
    FsPicos,
    #[serde(rename = "dummy")]
    Dummy,
    #[serde(rename = "dummy24")]
    Dummy24,
    #[serde(rename = "dummy48")]
    Dummy48,
}

impl std::fmt::Display for SwitchModel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Aruba => write!(f, "aruba"),
            Self::Aruba2540 => write!(f, "aruba2540"),
            Self::ArubaAosCx => write!(f, "aruba-aos-cx"),
            Self::ArubaCx6100 => write!(f, "aruba-cx6100"),
            Self::FsPicos => write!(f, "fs-picos"),
            Self::Dummy => write!(f, "dummy"),
            Self::Dummy24 => write!(f, "dummy24"),
            Self::Dummy48 => write!(f, "dummy48"),
        }
    }
}
