/*
 * 
 *
 * HWaaS NetCtrl API
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VlanId : Wrapper type for different VLAN IDs potentially used for different use cases.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VlanId {
    /// Standard 802.1q ID.
    #[serde(rename = "vlan_id")]
    pub vlan_id: i32,
}

impl VlanId {
    /// Wrapper type for different VLAN IDs potentially used for different use cases.
    pub fn new(vlan_id: i32) -> VlanId {
        VlanId {
            vlan_id,
        }
    }
}

