[workspace]
resolver = "3"
members = [
  "contextapi",
  "context_data_structures",
  "contextapi-workspace-hack",
  "net_ctrl_client",
  "image_api",
  "db_interaction",
  "machine_ops_lib",
  "machine_ops",
  "contextapi",
  "error_utils",
  "remote_client",
  "net_ctrl_client_wrapper",
]

[workspace.metadata.crane]
name = "contextapi"

[workspace.package]
version = "5.0.0"
edition = "2024"

# Default lints. Members SHOULD use these lints.
# See  https://doc.rust-lang.org/cargo/reference/workspaces.html#the-lints-table
[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
error_utils.path = "./error_utils"
context_data_structures.path = "./context_data_structures"
db_interaction.path = "./db_interaction"
machine_ops_lib.path = "./machine_ops_lib"
net_ctrl_client_wrapper.path = "./net_ctrl_client_wrapper"
image_api.path = "./image_api"
remote_client.path = "./remote_client"
net_ctrl_client.path = "./net_ctrl_client"
contextapi.path = "./contextapi"
remote-usb.path = "../remote-hands/remote-usb"
hunt.path = "../hunt"
aide = { version = "0.13", features = [
  "axum",
  "axum-multipart",
  "axum-extra",
  "axum-headers",
  "axum-ws",
  "macros",
] }
anyhow = "1"
axum = { version = "0.7", features = ["json", "macros", "multipart", "ws"] }
either = { version = "1", features = ["use_std"] }
assert_fs = "1"
chrono = { version = "0.4", default-features = false, features = [
  "std",
  "clock",
  "serde",
] }
clap = { version = "4.4", features = ["derive"] }
deadpool-diesel = { version = "0.6", features = ["sqlite", "rt_tokio_1"] }
diesel = { version = "2", default-features = false, features = [
  "chrono",
  "sqlite",
  "returning_clauses_for_sqlite_3_35",
] }
diesel_migrations = { version = "2", default-features = false, features = [
  "sqlite",
] }
futures = "0.3"
rand = "0.8.5"
reqwest = { version = "0.13", default-features = false, features = [
  "json",
  "stream",
  "rustls-no-provider",
] }
reqwest-middleware = { version = "0.5", features = ["json"] }
# NOTE(hartan): This is only a transient dependency, but we specify it here to
# define the features we expect once. Otherwise, it appears the
# `default-features` are set, which will pull in `aws-lc-sys` as additional
# crypto backend next to `ring`, which is already requested by other crates we
# use.
rustls = { version = "0.23", default-features = false, features = [
  "logging",
  "ring",
  "std",
  "tls12",
] }
schemars = { version = "0.8.0", default-features = false, features = [
  "derive",
  "uuid",
  "uuid1",
] }
serde = { version = "1", default-features = false, features = [
  "derive",
  "std",
] }
serde_json = { version = "1.0.86" }
strum_macros = { version = "0.26", default-features = false }
tokio = { version = "1.43", features = [
  "io-util",
  "macros",
  "net",
  "rt-multi-thread",
  "sync",
  "tracing",
  "signal",
  "time",
] }
tracing = "0.1"
trait-variant = "0.1"
uuid = { version = "1", features = ["v4", "fast-rng", "serde"] }
url = { version = "2", features = ["serde"] }
wiremock = "0.6"
