[package]
name = "contextapi"
version = "5.0.0"
edition = "2021"
license = "Apache-2.0"

[lib]
name = "context_api_lib"
path = "src/lib.rs"

[[bin]]
name = "contextapi"
path = "src/main.rs"

[[bin]]
name = "openapi-generator"
path = "src/bin/openapi-generator.rs"

[lints]
workspace = true

[dependencies]
aide.workspace = true
async-stream = "0.3.5"
async-trait = { version = "0.1.68" }
axum.workspace = true
chrono.workspace = true
clap.workspace = true
context_data_structures.workspace = true
db_interaction.workspace = true
diesel.workspace = true
dashmap = { version = "5.5.0", features = ["serde"] }
error_utils.workspace = true
futures.workspace = true
machine_ops_lib = { workspace = true, features = ["cli"] }
net_ctrl_client_wrapper.workspace = true
image_api.workspace = true
remote_client.workspace = true
sd-notify = "0.4.0"
tokio-stream = "0.1"
tokio-tungstenite = "0.24"
tokio-util = { version = "0.7.8", default-features = false }
tower = { version = "0.4" }
tracing.workspace = true
trait-variant.workspace = true
uuid.workspace = true
tower-http = { version = "0.6", default-features = false, features = [
  "trace",
  "request-id",
  "limit",
  "timeout",
  "cors",
] }
schemars = { version = "0.8.0", features = ["uuid", "uuid1", "derive"] }
hunt.workspace = true
reqwest-middleware.workspace = true
error-stack = "0.4.1"
sha2 = "0.10.6"
hex = "0.4.3"
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
url.workspace = true
remote-usb.workspace = true
contextapi-workspace-hack = { version = "0.1", path = "../contextapi-workspace-hack" }
bytesize = { version = "2.0.1", features = ["serde"] }

[dev-dependencies]
assert_fs.workspace = true
assert-json-diff = "2"
test-log = "0.2"
env_logger = "0.10"
wiremock.workspace = true
tracing-test = "0.2"
db_interaction = { workspace = true, features = ["test_utils"] }
reqwest = { workspace = true, default-features = false, features = [
  "hickory-dns",
] }
remote-usb = { workspace = true, features = ["usb-serial"] }
