[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "remote_client"
publish = false
readme = "README.md"
repository.workspace = true
version = "0.1.0"

[lib]
name = "remote_client"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
axum.workspace = true
db_interaction.workspace = true
reqwest.workspace = true
tracing.workspace = true
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
