[package]
name = "machine-ops"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "machine-ops"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1"
contextapi.workspace = true
db_interaction.workspace = true
machine_ops_lib = { workspace = true, features = ["cli"] }
clap.workspace = true
diesel.workspace = true
net_ctrl_client_wrapper.workspace = true
remote_client.workspace = true
reqwest.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = "0.3"
contextapi-workspace-hack = { version = "0.1", path = "../contextapi-workspace-hack" }

[dev-dependencies]
assert_cmd = "2"
assert_fs.workspace = true
predicates = "3"
db_interaction = { workspace = true, features = ["test_utils"] }
wiremock.workspace = true
tracing-test = "0.2"
