[package]
authors.workspace = true
description = "Arbitrary auxiliary devices for the `remote-hands` service"
default-run = "remote-auxiliary"
edition.workspace = true
license.workspace = true
name = "remote-auxiliary"
publish = false
readme = "README.md"
repository.workspace = true
version = "1.0.0"

[lib]
name = "remote_auxiliary"
path = "src/lib.rs"

[[bin]]
name = "remote-auxiliary"
path = "src/main.rs"

[[bin]]
name = "remote-auxiliary-openapi-generator"
path = "src/bin/openapi-generator.rs"

[lints]
workspace = true

[dependencies]
aide.workspace = true
axum.workspace = true
enum_dispatch.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
remote-axum.workspace = true
remote-init.workspace = true
reqwest.workspace = true
tracing.workspace = true
tokio.workspace = true
urlencoding.workspace = true
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
