# SPDX-FileCopyrightText: Copyright 2026 secunet Security Networks AG <https://www.secunet.com>
#
# SPDX-License-Identifier: Apache-2.0

# this file contains the some helper funtions for VLAN interface creation.
# It has impact on the deployment as it is used by the ws-gateway module.
# In addition it simplifies the NixOS integration setup for the ws-gateway, too.
{ lib
, prefix ? "wsn"
, networkFilePrefix ? "40-"
,
}:
let
  # Uses a prefix and a number to create a new (vlan)interface name
  # Example: vlanIfaceName 6 -> "wsn6"
  vlanIfaceName = index: prefix + builtins.toString index;

  # Accepts a base interface name and exposes a function which accepts a number.
  # Construct vlan configs with incremented vlan ids until the passed number is reached.
  # Example: ((vlanItemsGen "eth1") 2) -> [ { id = 1; interface = "eth1"; } { id = 2; interface = "eth1"; } ]
  vlanItemsGen =
    interface:
    builtins.genList (id: {
      inherit interface;
      id = id + 1;
    });

  # Based on a list generated by vlanItemsGen this function pulls out the id and creates a unique vlan interface name.
  # This results in one big attrSet with the desired vlan interface names and their corresponding vlanConfigItem.
  # Example: vlanConfigGen [ { id = 1; interface = "eth1"; } { id = 2; interface = "eth1"; } ]
  #            -> [ { wsn1 = { id = 1; interface = "eth1"; }; wsn2 = { id = 2; interface = "eth1"; } } ]
  vlanConfigGen = builtins.groupBy (x: vlanIfaceName x.id);

  # combines all functions above to generate a vlan config with ascending VLAN IDs up to numberOfVlans on baseInterface.
  vlanConfig =
    { baseInterface, numberOfVlans }:
    lib.attrsets.mapAttrs (_: lib.lists.last) (
      vlanConfigGen ((vlanItemsGen baseInterface) numberOfVlans)
    );

  # A systemd-networkd config to set a interface into promiscuous mode
  promiscConfigItem = name: {
    inherit name;
    linkConfig = {
      Promiscuous = true;
    };
    networkConfig = {
      LinkLocalAddressing = "no";
    };
  };

  # A systemd-networkd config attrset for given interfaces
  promiscConfig =
    { interfaces }:
    builtins.listToAttrs (
      map
        (name: {
          name = lib.strings.concatStrings [
            networkFilePrefix
            name
          ];
          value = promiscConfigItem name;
        })
        interfaces
    );
in
{
  inherit vlanConfig vlanIfaceName promiscConfig;
}
