[package]
name = "resource-calculator"
version = "0.1.0"
edition = "2021"
license="Apache-2.0"

[[bin]]
name = "resource-calculator"
path = "src/main.rs"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9.25"
clap = { version = "4.3.19", features = ["derive"] }
cli-table = "0.4.6"
daggy = "0.8.0"
error-stack = "0.4.0"
csv = "1.2"
