[package]
name = "aruba_structs"
version = "0.1.0"
edition = "2021"
license="Apache-2.0"

[lib]
name = "aruba_structs"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
schemars = "0.8"
aruba-switch-mock-workspace-hack = { version = "0.1", path = "../aruba-switch-mock-workspace-hack" }

[lints]
workspace = true
