[package]
name = "remote-axum"
edition = "2021"
version = "1.0.0"
license = "Apache-2.0"

[lib]
name = "remote_axum"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
aide = { version = "0.13", features = ["axum", "axum-extra", "macros"] }
axum = "0.7"
hunt.workspace = true
sd-notify = "0.4"
serde = "1"
serde_json = "1"
remote-init.workspace = true
tokio = { version = "1", features = ["signal", "sync"] }
tracing = "0.1"
remote-hands-workspace-hack = { version = "0.1", path = "../remote-hands-workspace-hack" }
