[package]
authors.workspace = true
description = "Shared bootstrapping of an axum router for remote-hands components"
edition.workspace = true
license.workspace = true
name = "remote-axum"
publish = false
readme = "README.md"
repository.workspace = true
version = "1.0.0"

[lib]
name = "remote_axum"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
aide.workspace = true
axum.workspace = true
hunt.workspace = true
sd-notify.workspace = true
serde.workspace = true
serde_json.workspace = true
remote-init.workspace = true
tokio.workspace = true
tracing.workspace = true
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
