[workspace]
resolver = "3"
members = [
  "remote-hands-workspace-hack",
  "remote-init",
  "remote-axum",
  "remote-serial",
  "remote-power",
  "remote-usb",
  "remote-auxiliary",
]

[workspace.metadata.crane]
name = "remote-hands"

[workspace.package]
version = "1.0.0"
edition = "2024"

# Default lints. Members SHOULD use these lints.
# See  https://doc.rust-lang.org/cargo/reference/workspaces.html#the-lints-table
[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
hunt.path = "../hunt"
remote-init.path = "./remote-init"
remote-axum.path = "./remote-axum"
serde = { version = "1.0", features = ["derive"] }
