[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "net_ctrl_client_wrapper"
publish = false
readme = "README.md"
repository.workspace = true
version = "0.1.0"


[lib]
name = "net_ctrl_client_wrapper"
path = "src/lib.rs"

[lints]
workspace = true

[dependencies]
hunt.workspace = true
reqwest-middleware.workspace = true
net_ctrl_client.workspace = true
db_interaction.workspace = true
