[package]
name = "rpi-status-display"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[[bin]]
name = "rpi-status-display"
path = "src/main.rs"

[lints.rust]
unsafe_code = "forbid"

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
embedded-graphics = "0.8.0"
rppal = { version = "0.14.1", features = ["hal"] }
ssd1306 = "0.8.0"
sh1106 = "0.5.0"
embedded-hal = "1.0.0-alpha.9"
